version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    # volumes:
    #   - ./volumes/MongoDB:/data/db
    networks:
      - mongo-network
  nctl:
    container_name: nctl
    build:
      context: ../.
      dockerfile: docker/Dockerfile.nctl
    tty: true
    ports:
      - 11101-11105:11101-11105
      - 14101-14105:14101-14105
      - 18101-18105:18101-18105
      - 22101-22105:22101-22105
    networks:
      - casper-network
  casper-client:
    container_name: casper-client
    build:
      context: .
      dockerfile: Dockerfile.casper-client
    tty: true
    networks:
      - casper-network
networks:
    mongo-network:
      driver: bridge
    casper-network:
      driver: bridge
