version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/MongoDB:/data/db
    networks:
      - mongo-network

networks:
    mongo-network:
      driver: bridge
